on:
  workflow_dispatch:
    branches:
      - "main"
name: 🚀 Deploy website
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Setup
      run: |
          cd blog && cp wp-config-sample.php wp-config.php
          sed -i "s/database_name_here/${{ secrets.DB_NAME }}/" wp-config.php
          sed -i "s/username_here/${{ secrets.DB_USER }}/" wp-config.php
          sed -i "s/password_here/${{ secrets.DB_PASSWORD }}/" wp-config.php
          sed -i "s/auth_key/${{ secrets.AUTH_KEY }}/" wp-config.php
          sed -i "s/secure_auth_key/${{ secrets.SECURE_AUTH_KEY }}/" wp-config.php
          sed -i "s/logged_in_key/${{ secrets.LOGGED_IN_KEY }}/" wp-config.php
          sed -i "s/nonce_key/${{ secrets.NONCE_KEY }}/" wp-config.php
          sed -i "s/auth_salt/${{ secrets.AUTH_SALT }}/" wp-config.php
          sed -i "s/secure_auth_salt/${{ secrets.SECURE_AUTH_SALT }}/" wp-config.php
          sed -i "s/logged_in_salt/${{ secrets.LOGGED_IN_SALT }}/" wp-config.php
          sed -i "s/nonce_salt/${{ secrets.NONCE_SALT }}/" wp-config.php
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
